version: 0.2

phases:
  pre_build:
    commands:
       - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/i7h1a8h4
  build:
    commands:
      - cd backend
      - docker build -t mern-backend-69 .
  post_build:
    commands:
       - docker tag mern-backend-69:latest public.ecr.aws/i7h1a8h4/mern-backend-69:latest
       - docker push public.ecr.aws/i7h1a8h4/mern-backend-69:latest
       - cd ..
       - printf '[{"name":"rani-container","imageUri":"public.ecr.aws/i7h1a8h4/mern-backend-69:latest"}]' > imagedefinitions.json


artifacts:
  files: imagedefinitions.json     